### ISSUE TITLE
Writing the solution in Python 3

### ISSUE THREAD

**Issue by chuaweijie** [kamyu104/GoogleKickStart-2021#3]
Hi! I noticed that the solutions are written in Python 2. If I am able to rewrite them into Python 3 during my studies, may I contribute them to this repository? How should I structure the directories?

**Comment by kamyu104** [comment]
- Thank you for your kind contribution.
  - Currently, I prefer to keep the repositories intact.
  - The reasons are as follows.

**Why Python2**
* **Pros**
  - Compatible with PyPy2.
  - Compatible with Python3/PyPy3 by `2to3`.
  - Easily evaluate the performance in both Python2/PyPy2 and Python3/PyPy3.
  - Most contest platforms support PyPy2.
* **Cons**
  - Python2 as a language has been sunset as of 2020-01-01.

**Why Python3**
* **Pros**
   - Compatible with PyPy3.
   - More convenient syntax, libraries, and performance improvements.
* **Cons**
   - Inompatible with Python2/PyPy2.
   - Running my solutions in PyPy3  is usually slower than in PyPy2.
   - The online platform did not support PyPy3 until 2021-04. 
       - Some solutions require PyPy2 or PyPy3 for better performance.

**When to Write Python3**
   - Old  Python2/PyPy2 solutions could be converted automatically to Python3/PyPy3 by `2to3`.
       - No need to keep generated Python3/PyPy3 solutions.
   - The online platform no longer supports Python2/PyPy2 since 2021-11. 
       - PyPy3 is fully supported now on the online platform.
       - I will write new solutions in Python3/PyPy3 with `*.py3` file extension in the future.
